const express = require("express");
const pgitPolicyRouter = require('./pgitPolicy');
const pgitPolSectionRouter = require('./pgitPolSection');
const PGITPOLRISKADDLINFORouter = require('./PGITPOLRISKADDLINFO');
const pgitPolRiskCoverRouter = require('./pgitPolRiskCover');
const PGITPOLDEDUCTIBLERouter = require('./PGITPOLDEDUCTIBLE');
const pgitPolConditionRouter = require('./pgitPolCondition');
const pgitPolBrokerRouter = require('./pgitPolBroker');
const pgitTaxDtlRouter = require('./pgitTaxDtl');
const pgitPolChargeRouter = require('./pgitPolCharge');
const pgitPolApplCurrRouter = require('./pgitPolApplCurr');
const pgitPolInstPremRouter = require('./pgitPolInstPrem');
const pgitAcntDocRouter = require('./pgitAcntDoc');
const pcomCodesRouter = require('./pcomCodes');
const pcomAppParameterRouter = require('./pcomAppParameter');
const PGITPOLHYPOTHECATIONRouter = require('./PGITPOLHYPOTHECATION');
const PGITPOLPREVINSDTLRouter = require('./PGITPOLPREVINSDTL'); 
const PGITPOLPREMCOMPSHEETRouter = require('./PGITPOLPREMCOMPSHEET');
const PGITPOLINSTCHARGERouter = require('./PGITPOLINSTCHARGE');
const PGITRIINTERFACERouter = require('./PGITRIINTERFACE');
const PGITRIPROPTTYDTLPGRouter = require('./PGITRIPROPTTYDTLPG');
const PGITRIPROPTTYALLOCRouter = require('./PGITRIPROPTTYALLOC');
const pgithPolicyRouter = require('./pgithPolicy');
const pgithPolSectionRouter = require('./pgithPolSection');
const pgithPolRiskAddlInfoRouter = require('./pgithPolRiskAddlInfo');
const pgithPolRiskCoverRouter = require('./pgithPolRiskCover');
const pgithPolRiskSmiRouter = require('./pgithPolRiskSmi');
const pgithPolDeductibleRouter = require('./pgithPolDeductible');
const pgithPolConditionRouter = require('./pgithPolCondition');
const pgithPolPrevInsDtlRouter = require('./pgithPolPrevInsDtl');
const pgithPolChargeRouter = require('./pgithPolCharge');
const pgithPolApplCurrRouter = require('./pgithPolApplCurr');
const pgithPolBrokerRouter = require('./pgithPolBroker');
const pgithPolHypothecationRouter = require('./pgithPolHypothecation');
const pgithPolInstPremRouter = require('./pgithPolInstPrem');
const pgitFacOutRouter = require('./pgitFacOut');
const pgitRiPolRiskDtlRouter = require('./pgitRiPolRiskDtl');
const pgitFacPlaceShareRouter = require('./pgitFacPlaceShare');
const pgitFacPlacePcDtlRouter = require('./pgitFacPlacePcDtl');
const pgitFacCustRouter = require('./pgitFacCust');
const pgitFacCommTaxRouter = require('./pgitFacCommTax');
const pgitFacCustRetroRouter = require('./pgitFacCustRetro');
const pgitPolScheduleRouter = require('./pgitPolSchedule');
const pgitPolInwardRouter = require('./pgitPolInward');
const pgitPolCoinPartCustRouter = require('./pgitPolCoinPartCust');
const pgitPolCoinCommRouter = require('./pgitPolCoinComm');
const PGITRIPROPTTYALLOCCUSTRouter = require('./PGITRIPROPTTYALLOCCUST');
const PGITRIPROPTTYALLOCRCRouter = require('./PGITRIPROPTTYALLOCRC');
const pgitFacPlaceRiskDtlRouter = require('./pgitFacPlaceRiskDtl');
const router = express.Router();
const lmCompanyRoutes=require('./lmCompanyRoutes');
const class_of_busRoute = require('./class_of_busRoute');
const policyFields =require('./policyFieldsRoute');
const mainTemplateRoute = require("./mainTemplateRoute");
const instancePolicy_01Route = require("./policyInstancesRoute");
const polOneInstCode = require("./policyOneInstCodeRoute");
const oneProgProdInst = require("./oneProgProdeInstRoute");
const listOfInst = require('./listOfInstanceRoute');
const policyLov = require('./policyLovRoute');
const secForOneProd = require('./secForOneProdRoute');
const pcom_codes = require('./pcom_codes_pctypeRoute');
const pcom_app = require('./pcom_app_paracodeRoute');
const riskLov = require('./riskLovRoute');
const riskField = require('./riskFieldRoute');
const sectionfields = require('./sectionFieldRoute');
const modernDropDown = require('./modernDropDownRoute');
const dropDown = require('./dropdownRoute');
const riskSmi = require('./riskSmiFieldRoute');
const riskSmiLovFieldRoute = require('./riskSmiLovFieldRoute');
const pgit_pol_risk_cover = require('./pgitPolRiskCover');
const pgit_pol_risk_smi = require('./PGITPOLRISKSMI');
const riskCoverFieldRoute = require('./riskCoverFieldRoute');
const riskCoverLovRoute = require('./riskCoverLovRoute');
const riskDiscountFieldRoute = require('./riskDiscountFieldRoute');
const riskDiscountLov = require('./riskDiscountLovRoute');
const riskDeductible = require('./riskDeductibleFieldRoute');
const riskDeductibleLov = require('./riskDeductibleLovRoute');
const dsCode = require('./ds_codeRoute');
const polConditionFieldRoute = require('./polConditionFieldRoute');
const polConditionLovRoute = require('./polConditionLovRoute');
const polPreInsDtlField = require('./polPrevInsDtlFieldRoute');
const polPreInsDtlLov = require('./polPreInsDtlLovRoute');
const polChargeField = require('./polChargeFieldRoute');
const polChargeLov = require('./polChargeLovRoute');
const polApplCurrField = require('./polApplCurrFieldRoute');
const polApplCurrLovRoute = require('./polApplCurrLovRoute');
const polInstPremFieldRoute = require('./polInstPremFieldRoute');
const polInstPremLov = require('./polInstPremLovRoute');
const polBrokerField = require('./polBrokerFieldRoute');
const polBrokerLov = require('./polBrokerLovRoute');
const polHypoField = require('./polHypoFieldRoute');
const polHypoLovRoute = require('./polHypoLovRoute');
const screenSetup = require('./screenSetupRoute');
const Calculate_Premium = require('./P_CALC_PREMIUMRoute');
const compSheetField = require('./compSheetRoute');
const POL_APPR_VALRoute = require('./POL_APPR_VALRoute');
const GET_EXCH_RATERoute  = require('./GET_EXCH_RATERoute');
const instcharge =require('./polInstChargeFieldRoute');
const PGIT_POL_PREM_DTLRoute =require('./PGIT_POL_PREM_DTLRoute');
const sdrop = require ('./simpleDropdownRoutes.js');
const simpleDropdownService = require('./simpleDropdownRoutes.js');
const appBtn = require('./approveBtnRoute.js');
const riInterfaceField = require('./pgitRiInterfaceFieldRoute.js');
const riTtyDtlPgField = require ('./pgitRiPropTtyDtlPgFieldRoute.js');
const riTtyAllocField = require ('./pgitRiPropTtyAllocFieldRoute.js');
const facPlacementFieldRoute = require('./facPlacementFieldRoute.js');
const facShareDtlFieldRoute = require('./facShareDtlFieldRoute.js');
const placementFieldRoute = require('./placementFieldRoute.js');
const facPolDtlFieldRoute = require('./facPolDtlFieldRoute.js');
const pgitFacCustFieldRoute = require('./pgitFacCustFieldRoute.js');
const pgitFacCommTaxFieldRoute = require('./pgitFacCommTaxFieldRoute.js');
const pgitFacPlacePcDtlFieldRoute = require('./pgitFacPlacePcDtlFieldRoute.js');
const pgitFacCustRetroFieldRoute = require('./pgitFacCustRetroFieldRoute.js');
const PR_FPRD_FPPD_CALCRoute = require('./PR_FPRD_FPPD_CALCRoute.js');
const PrFacCustCalcRoute = require('./PrFacCustCalcRoute.js');
const prFacCommCalcRoute = require('./prFacCommCalcRoute.js');
const prFacRetroCalcRoute = require('./prFacRetroCalcRoute.js');
const prCalcFacCustPremTaxRoute = require('./prCalcFacCustPremTaxRoute.js');
const prCalcFacCommTaxRoute = require('./prCalcFacCommTaxRoute.js');
const prCalcRetroCustPremTaxRoute = require('./prCalcRetroCustPremTaxRoute.js');
const prDefaultFacPercRoute = require('./prDefaultFacPercRoute.js');
const prClearFacPercRoute = require('./prClearFacPercRoute.js');
const vatTaxFieldRoute = require('./vatTaxFieldRoute.js');
const endBlkSetupRoute = require('./endBlkSetupRoute.js');
const endBtnRoute = require('./endBtnRoute.js');
const polAcntEntryRoute=require('./polAcntEntryRoute.js');
const inwardField=require('./pgitPolInwardFieldRoute.js');
const coinPartCustField=require('./pgitPolCoinPartCustFieldRoute.js');
const pgitPolCoinCommField=require('./pgitPolCoinCommFieldRoute.js');
const PolInwardLov=require('./pgitPolInwardLovRoute.js');
const CoinPartCustLov=require('./pgitPolCoinPartCustLovRoute.js');
const pgitPolCoinCommLov=require('./pgitPolCoinCommLovRoute.js');
const riTtyAllocCustField=require('./pgitRiPropTtyAllocCustFieldRoute.js');
const pgitRiPropAllocRcFieldRoute=require('./pgitRiPropAllocRcFieldRoute.js');
const riConCanBtn = require('./riConCanBtnRoute.js');
const ttyApproveBtn = require('./ttyApproveBtnRoute.js');
const pgitFacPlaceRiskDtlFieldRoute = require('./pgitFacPlaceRiskDtlFieldRoute.js');

//////////////////////////////////////////////////////////////////////////////////////////////////




router.use('/company',lmCompanyRoutes);
router.use('/businesses', class_of_busRoute);
router.use('/policyFields',policyFields);
router.use('/templates/policy',mainTemplateRoute);
router.use('/policy/instance',instancePolicy_01Route);
router.use('/policy/instanceCode',polOneInstCode);
router.use('/program/product/instance',oneProgProdInst);
router.use('/listOfInst',listOfInst);
router.use('/pgitPolicy', pgitPolicyRouter);
router.use('/pgitPolSection', pgitPolSectionRouter);
router.use('/risk', PGITPOLRISKADDLINFORouter);
router.use('/pgitPolRiskCover', pgitPolRiskCoverRouter);
router.use('/PGITPOLDEDUCTIBLE', PGITPOLDEDUCTIBLERouter);
router.use('/pgitPolCondition', pgitPolConditionRouter);
router.use('/pgitPolBroker', pgitPolBrokerRouter);
router.use('/pgitTaxDtl', pgitTaxDtlRouter);
router.use('/pgitPolCharge', pgitPolChargeRouter);
router.use('/pgitPolApplCurr', pgitPolApplCurrRouter);
router.use('/pgitPolInstPrem', pgitPolInstPremRouter);
router.use('/pgitAcntDoc', pgitAcntDocRouter);
router.use('/policyLov',policyLov);
router.use('/secForOneProd',secForOneProd);
router.use('/lovspc',pcom_codes);
router.use('/lovpara',pcom_app);
router.use('/riskLov',riskLov);
router.use('/riskField',riskField);
router.use('/sectionField',sectionfields);
router.use('/modernDropDown',modernDropDown);
router.use('/dropDown',dropDown);
router.use('/riskSmi', riskSmi);
router.use('/riskSmiLovField', riskSmiLovFieldRoute);
router.use('/riskCover', riskCoverFieldRoute);
router.use('/riskCoverLov', riskCoverLovRoute);
router.use('/pcomCodes', pcomCodesRouter);
router.use('/pcomAppParameter', pcomAppParameterRouter);
router.use('/pgitPolRiskCover', pgit_pol_risk_cover);
router.use('/pgitPolRiskSmi', pgit_pol_risk_smi);
router.use('/riskDiscountField', riskDiscountFieldRoute);
router.use('/riskDiscountLov', riskDiscountLov);
router.use('/riskDeductibleField', riskDeductible);
router.use('/riskDeductibleLov', riskDeductibleLov);
router.use('/dsCode',dsCode);
router.use('/polConditionField', polConditionFieldRoute);
router.use('/polConditionLov', polConditionLovRoute);
router.use('/polPrevInsDtlField', polPreInsDtlField);
router.use('/polPrevInsDtlLov', polPreInsDtlLov);
router.use('/polChargeField', polChargeField);
router.use('/polChargeLov', polChargeLov);
router.use('/polApplCurrField', polApplCurrField);
router.use('/polApplCurrLov', polApplCurrLovRoute);
router.use('/polInstPremField', polInstPremFieldRoute);
router.use('/polInstPremLov', polInstPremLov);
router.use('/polBrokerField', polBrokerField);
router .use('/polBrokerLov', polBrokerLov);     
router.use('/PGITPOLHYPOTHECATION', PGITPOLHYPOTHECATIONRouter);
router.use('/polHypoField', polHypoField);
router.use('/polHypoLov', polHypoLovRoute);
router.use('/PGITPOLPREVINSDTL', PGITPOLPREVINSDTLRouter);
router.use('/screenSetup',screenSetup);
router.use('/CalculatePremium',Calculate_Premium);
router.use('/compSheetField',compSheetField);
router.use('/PGITPOLPREMCOMPSHEET', PGITPOLPREMCOMPSHEETRouter);
router.use('/approval',POL_APPR_VALRoute);
router.use('/amount',GET_EXCH_RATERoute);
router.use ('/instChargeField',instcharge);
router.use('/polInstCharge', PGITPOLINSTCHARGERouter);
router.use('/preDtls',PGIT_POL_PREM_DTLRoute);
router.use('/sdrop',simpleDropdownService);
router.use('/approveBtn',appBtn);

router.use('/treatyTab1',riInterfaceField);
router.use('/treatyTab2',riTtyDtlPgField);
router.use('/treatyTab3',riTtyAllocField);
router.use('/PGITRIINTERFACE', PGITRIINTERFACERouter);
router.use('/PGITRIPROPTTYDTLPG', PGITRIPROPTTYDTLPGRouter);
router.use('/PGITRIPROPTTYALLOC', PGITRIPROPTTYALLOCRouter);



router.use('/pgithPolicy', pgithPolicyRouter);
router.use('/pgithPolSection', pgithPolSectionRouter);
router.use('/pgithPolRiskAddlInfo', pgithPolRiskAddlInfoRouter);
router.use('/pgithPolRiskCover', pgithPolRiskCoverRouter);
router.use('/pgithPolRiskSmi', pgithPolRiskSmiRouter);
router.use('/pgithPolDeductible', pgithPolDeductibleRouter);
router.use('/pgithPolCondition', pgithPolConditionRouter);
router.use('/pgithPolPrevInsDtl', pgithPolPrevInsDtlRouter);
router.use('/pgithPolCharge', pgithPolChargeRouter);
router.use('/pgithPolApplCurr', pgithPolApplCurrRouter);
router.use('/pgithPolBroker', pgithPolBrokerRouter);
router.use('/pgithPolHypothecation', pgithPolHypothecationRouter);
router.use('/pgithPolInstPrem', pgithPolInstPremRouter);
router.use('/facPlacementField',facPlacementFieldRoute);
router.use('/facShareDtlField',facShareDtlFieldRoute);
router.use('/placementField',placementFieldRoute);
router.use('/facPolDtlField',facPolDtlFieldRoute);
router.use('/pgitFacCustField',pgitFacCustFieldRoute);  
router.use('/pgitFacCommTaxField',pgitFacCommTaxFieldRoute);
router.use('/pgitFacPlacePcDtlField',pgitFacPlacePcDtlFieldRoute);
router.use('/pgitFacCustRetroField',pgitFacCustRetroFieldRoute);
router.use('/vatTaxField',vatTaxFieldRoute);
router.use('/pgitFacOut', pgitFacOutRouter);
router.use('/pgitRiPolRiskDtl', pgitRiPolRiskDtlRouter);
router.use('/pgitFacPlaceShare', pgitFacPlaceShareRouter);
router.use('/pgitFacPlacePcDtl', pgitFacPlacePcDtlRouter);
router.use('/pgitFacCust', pgitFacCustRouter);
router.use('/pgitFacCommTax', pgitFacCommTaxRouter);
router.use('/pgitFacCustRetro', pgitFacCustRetroRouter);
router.use('/prFprdFppdCalc', PR_FPRD_FPPD_CALCRoute);
router.use('/prFacCustCalc',PrFacCustCalcRoute);
router.use('/prFacCommCalc', prFacCommCalcRoute);
router.use('/prFacRetroCalc', prFacRetroCalcRoute);
router.use('/prCalcFacCustPremTax', prCalcFacCustPremTaxRoute);
router.use('/prCalcFacCommTax', prCalcFacCommTaxRoute);
router.use('/prCalcRetroCustPremTax', prCalcRetroCustPremTaxRoute);
router.use('/endBlkSetup',endBlkSetupRoute);
router.use('/pgitPolSchedule', pgitPolScheduleRouter);
router.use('/polAcntEntry',polAcntEntryRoute);
router.use('/pgitPolInward', pgitPolInwardRouter);
router.use('/pgitPolCoinPartCust', pgitPolCoinPartCustRouter);
router.use('/pgitPolCoinComm', pgitPolCoinCommRouter);
router.use('/inwardField',inwardField);
router.use('/coinPartCustField',coinPartCustField);
router.use('/CoinCommField',pgitPolCoinCommField);
router.use('/PolInwardLov',PolInwardLov);
router.use('/CoinPartCustLov',CoinPartCustLov);
router.use('/CoinCommLov',pgitPolCoinCommLov);
router.use('/ttyPartCustField',riTtyAllocCustField);
router.use('/ttyRiskClassField',pgitRiPropAllocRcFieldRoute);
router.use('/PGITRIPROPTTYALLOCCUST', PGITRIPROPTTYALLOCCUSTRouter);
router.use('/PGITRIPROPTTYALLOCRC', PGITRIPROPTTYALLOCRCRouter);
router.use('/riConCanBtn', riConCanBtn);
router.use('/ttyApproveBtn', ttyApproveBtn);
router.use('/pgitFacPlaceRiskDtl', pgitFacPlaceRiskDtlRouter);
router.use('/pgitFacPlaceRiskDtlField', pgitFacPlaceRiskDtlFieldRoute);
router.use('/prDefaultFacPerc', prDefaultFacPercRoute);
router.use('/prClearFacPerc', prClearFacPercRoute);
router.use('/endBtn', endBtnRoute);




router.use('/pgitPolRiskCover', pgitPolRiskCoverRouter);
module.exports = router;
